import {
  name,
  tagline,
  description,
  nav,
  headerCta,
  marketing,
  about,
  footer,
  metadata,
} from "./marketing";

// App-internal content. Client components should import narrowly from ./marketing,
// so the full site object is not shipped in public marketing bundles.
export const site = {
  name,
  tagline,
  description,
  nav,
  headerCta,
  marketing,
  about,
  footer,
  metadata,
  designPartners: {
  headline: "Bring Compass a real operational problem.",
  subtitle: "We are working with operations leaders and founders to evaluate real decisions before implementation begins.",
  benefits: [
    "A structured operational investigation",
    "A comparison of evidence-supported interventions",
    "A prioritized finding and action plan",
    "Direct influence on the product roadmap",
  ],
  form: {
    headline: "Apply to become a design partner",
    fields: {
      name: "Full name",
      email: "Work email",
      companyName: "Company name",
      companySize: "Company size",
      role: "Your role",
      linkedinUrl: "LinkedIn URL",
      currentAiInitiatives: "Current AI initiatives",
      biggestChallenge: "Biggest operational challenge",
    },
    submit: "Submit application",
    success: "Thanks for applying! We'll be in touch within 2 business days.",
    error: "Something went wrong. Please try again.",
  },
  cta: "Become a design partner",
  ctaSecondary: "Start an investigation",
},
  assessment: {
  intro: {
    headline: "What decision are you trying to make?",
    body: "This is context gathering, not a form. Tell Compass about your workflow, systems, and goals so it can compare your situation against real-world implementations and produce a decision you can defend.",
    estimatedTime: "10\u201315 minutes",
    sections: "Problem, workflow, systems, constraints",
    questions: "Guided context about your operations",
    cta: "Begin",
  },
  sections: {
    "General": "We'll start by understanding the department, workflow, and desired outcome \u2014 focused on the business problem, not the technology.",
    "Workload": "Understanding the frequency, scale, and complexity of the work helps us determine whether intervention is worthwhile.",
    "Systems": "Your existing tools and data determine what's possible. We'll map the current technical landscape.",
    "Impact": "We'll assess the cost of the current workflow \u2014 in time, money, and missed opportunity.",
    "Risk": "Understanding risk, stability, and prior attempts helps us recommend the right level of intervention.",
    "Constraints": "Technical constraints, budget, and timeline define what's feasible. We'll factor these into every finding.",
  },
  complete: {
    headline: "Assessment complete.",
    body: "Your responses have been analyzed against comparable implementations. Your findings are ready below.",
    cta: "View Recommendations",
  },
},
  results: {
  headline: "Recommendations",
  subtitle: "Ranked by evidence quality, not opinion. Every finding is grounded in comparable implementations with displayed evidence strength, assumptions, and alternatives.",
  noResults: "No results found. Please complete the operational assessment first.",
  buildBlueprint: "View Implementation Plan",
  comparePaths: "Compare intervention paths",
},
  interventionComparison: {
  headline: "Compare intervention paths",
  noSelection: "Select an opportunity to compare intervention paths.",
  dimensions: ["Eligibility", "Suitability", "Expected outcome", "Effort", "Risk", "Time to value", "Human oversight", "Evidence strength"],
},
  blueprint: {
  headline: "Implementation Plan",
  sections: [
    "Problem",
    "Root cause",
    "Evidence-supported intervention",
    "Alternatives considered",
    "Why this path won",
    "Current workflow",
    "Future workflow",
    "Required systems",
    "Required APIs",
    "Required data",
    "Human roles",
    "Security and privacy",
    "Rollout plan",
    "Success metrics",
    "Risks and assumptions",
    "Expected impact",
    "Technical escalation level",
  ],
},
  evidenceLabels: {
  headline: "Evidence and assumptions",
  labels: {
    "user-provided": "User-provided evidence",
    "deterministic-analysis": "Deterministic analysis",
    "ai-inference": "AI inference",
    "hypothesis": "Hypothesis",
    "missing": "Missing information",
  },
  whatCouldChange: "What could change this finding",
  whyChose: "Why Compass chose this",
  whyRejected: "Why Compass rejected alternatives",
},
  contact: {
  email: "smithar106@gmail.com",
},
};
