import {
  name,
  tagline,
  description,
  nav,
  headerCta,
  marketing,
  about,
  footer,
  metadata,
} from "./marketing";

// App-internal content. Client components should import narrowly from ./marketing,
// so the full site object is not shipped in public marketing bundles.
export const site = {
  name,
  tagline,
  description,
  nav,
  headerCta,
  marketing,
  about,
  footer,
  metadata,
  designPartners: {
  headline: "Bring Compass a real operational problem.",
  subtitle: "We are working with operations leaders and founders to evaluate real decisions before implementation begins.",
  benefits: [
    "A structured operational investigation",
    "A comparison of evidence-supported interventions",
    "A prioritized finding and action plan",
    "Direct influence on the product roadmap",
  ],
  form: {
    headline: "Apply to become a design partner",
    fields: {
      name: "Full name",
      email: "Work email",
      companyName: "Company name",
      companySize: "Company size",
      role: "Your role",
      linkedinUrl: "LinkedIn URL",
      currentAiInitiatives: "Current AI initiatives",
      biggestChallenge: "Biggest operational challenge",
    },
    submit: "Submit application",
    success: "Thanks for applying! We'll be in touch within 2 business days.",
    error: "Something went wrong. Please try again.",
  },
  cta: "Become a design partner",
  ctaSecondary: "Start an investigation",
},
  interventionComparison: {
  headline: "Compare intervention paths",
  noSelection: "Select an opportunity to compare intervention paths.",
  dimensions: ["Eligibility", "Suitability", "Expected outcome", "Effort", "Risk", "Time to value", "Human oversight", "Evidence strength"],
},
  blueprint: {
  headline: "Implementation Plan",
  sections: [
    "Problem",
    "Root cause",
    "Evidence-supported intervention",
    "Alternatives considered",
    "Why this path won",
    "Current workflow",
    "Future workflow",
    "Required systems",
    "Required APIs",
    "Required data",
    "Human roles",
    "Security and privacy",
    "Rollout plan",
    "Success metrics",
    "Risks and assumptions",
    "Expected impact",
    "Technical escalation level",
  ],
},
  evidenceLabels: {
  headline: "Evidence and assumptions",
  labels: {
    "user-provided": "User-provided evidence",
    "deterministic-analysis": "Deterministic analysis",
    "ai-inference": "AI inference",
    "hypothesis": "Hypothesis",
    "missing": "Missing information",
  },
  whatCouldChange: "What could change this finding",
  whyChose: "Why Compass chose this",
  whyRejected: "Why Compass rejected alternatives",
},
  contact: {
  email: "smithar106@gmail.com",
},
};
